name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and release
        uses: davegarvey/grubble@v5
        with:
          push: true
          package-files: "package.json"
          preset: node
          create-pr: true
          auto-merge: true
